name: herfee
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.9.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  provider: ^6.1.5+1
  adaptive_theme: ^3.7.1+2
  flutter_localization: ^0.3.3
  shared_preferences: ^2.5.3
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.10.0
  flutter_svg: ^2.2.0
  supabase_flutter: ^2.10.0
  email_validator: ^3.0.0
  flutter_otp_text_field: ^1.5.1+1
  permission_handler: ^12.0.1
  image_picker: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/font/
    - assets/image/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/static/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true