// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXHVppJvr6tclcuOWp59vuWvmFGYNDsPc',
    appId: '1:626727018916:web:2a44a66144a9d4e97ca131',
    messagingSenderId: '626727018916',
    projectId: 'herfee-bfedb',
    authDomain: 'herfee-bfedb.firebaseapp.com',
    storageBucket: 'herfee-bfedb.firebasestorage.app',
    measurementId: 'G-F0VYX9VF2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPSNCwnKM8fYNzOF7hOdJWA0UiENXrOgc',
    appId: '1:626727018916:android:f6b49d5669c93b3a7ca131',
    messagingSenderId: '626727018916',
    projectId: 'herfee-bfedb',
    storageBucket: 'herfee-bfedb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQpjq4jzh_txPHHWqtTOm-3srklldI3QE',
    appId: '1:626727018916:ios:cef07a0caab67c267ca131',
    messagingSenderId: '626727018916',
    projectId: 'herfee-bfedb',
    storageBucket: 'herfee-bfedb.firebasestorage.app',
    iosBundleId: 'com.example.herfee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQpjq4jzh_txPHHWqtTOm-3srklldI3QE',
    appId: '1:626727018916:ios:cef07a0caab67c267ca131',
    messagingSenderId: '626727018916',
    projectId: 'herfee-bfedb',
    storageBucket: 'herfee-bfedb.firebasestorage.app',
    iosBundleId: 'com.example.herfee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXHVppJvr6tclcuOWp59vuWvmFGYNDsPc',
    appId: '1:626727018916:web:1b41034045320efd7ca131',
    messagingSenderId: '626727018916',
    projectId: 'herfee-bfedb',
    authDomain: 'herfee-bfedb.firebaseapp.com',
    storageBucket: 'herfee-bfedb.firebasestorage.app',
    measurementId: 'G-4MVFB00QPM',
  );
}
